name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Build and publish release binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Mark workspace as safe for git
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Run GoReleaser
      uses: docker://goreleaser/goreleaser-cross:v1.26.3-v2.16.0
      with:
        args: release --clean --config=.goreleaser.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
